routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//rota padrão para mostrar todos os usuários
Route::get('/', 'UsuarioController@create');

Route::get('usuario/exportar', 'UsuarioController@export')->name('exportar');
Route::resource('usuario', 'UsuarioController');

app/Usuario.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Usuario extends Model
{
    protected $fillable = ['method', 'nome', 'email'];
    protected $primaryKey = 'id';
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Usuario;
use Illuminate\Support\Facades\Mail;
use App\Mail\UserRegisteredMail;
use App\Exports\UsuarioFromView;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Support\Facades\DB;

class UsuarioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $usuarios = Usuario::all();
        return view('usuario.all')->with('usuarios', $usuarios);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('usuario.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (DB::table('usuarios')->where('email', $request->email)->count() == 0){ 
            $usuario = new Usuario();
            $usuario->email = $request->email;
            $usuario->nome = $request->nome;
            $usuario->save();
            return $this->registered($usuario);
        }else{
            return view('usuario.failure')->with('request', $request);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $usuario = Usuario::find($id);
        return view('usuario.edit')->with('usuario', $usuario);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $parametros = $request->all();
        $usuario = Usuario::find($id);
        $usuario->update($parametros);
        $usuario->save();
        return redirect('usuario');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $usuario = Usuario::find($id);
        $usuario->delete();
        return redirect('usuario');
    }

    public function registered($usuario){
        Mail::to($usuario->email)->send(new UserRegisteredMail($usuario));
        return $this->success($usuario);
    }

    public function success($usuario){
        return view('usuario.success')->with('usuario', $usuario);
    }
    
    public function export(){
        if (DB::table('usuarios')->count() > 0){
            return Excel::download(new UsuarioFromView, 'usuarios.xlsx');
        }else{
            return redirect('usuario')->with('erro', 'Não é possível baixar a planilha sem usuários cadastrados');
        }
    }
}

resources/views/usuario/all.blade.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa&family=Rubik&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{URL::asset('/css/all.css')}}">
    <link rel="shortcut icon" href="{{URL::asset('/image/favicon.ico')}}">
    <title>Usuários</title>
</head>
<body>
    
    <div class="container col-lg-5 col-md-8 col-sm-8 shadow p-3 mt-5 mb-5 bg-white">
        <div class="content">

            
            <div class="w-100">
                <div class="brand-div">
                    <img src="{{URL::asset('/image/brand.png')}}" class="align-left ml-3 brand-img" alt='shopmee brand'>
                </div>
                
                <div class="download-div text-right">
                    <a class="btn create align-right w-100" href="{{route('exportar')}}">
                        <img src="{{URL::asset('/image/excel.png')}}" class=" ml-3 download" alt='excel'>Download
                    </a>
                </div>
            </div>

            <div class="w-100">
                <h5 class="align-left mt-2 ml-3 text-secondary cadastred">Usuários cadastrados</h5>
                
                <a class="btn create" href="{{route('usuario.create')}}">
                    Criar Usuário
                </a>
               
            </div>

            <hr>

            @if (\Session::has('erro'))
                <h5 class="text-danger text-center">{!! \Session::get('erro') !!}</h5>
            @endif
                

            @foreach ($usuarios as $usuario)
            <div class="cards ml-3 mb-5">
                <div class="title w-100 shadow">
                    <p class="text-center">{{$usuario->nome}}</p>
                </div>

                <div class="card-content shadow">
                    <div class="nome mt-3 ml-3">
                        <p ><strong>Nome:</strong></p>
                        <ul>
                            <li>{{$usuario->nome}}</li>
                        </ul>
                    </div>

                    <div class="email mt-3 ml-3 mb-3">
                        <p ><strong>E-mail:</strong></p>
                        <ul>
                            <li>{{$usuario->email}}</li>
                        </ul>
                    </div>

                    <div class="buttons w-100 text-center">
                        <a class="btn edit mb-3" href="{{route('usuario.edit', $usuario->id)}}">
                            Editar
                        </a>
                        <form action="{{route('usuario.destroy', $usuario->id)}}" method="POST" class="destroy" onsubmit = 'return ConfirmDelete()'>
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger w-100 mb-3">Excluir</button>
                        </form>
                    </div>
                </div>
            </div>
            @endforeach
        </div>
    </div>


    {{-- Bootstrap --}}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous">
    </script>
    <script>
        function ConfirmDelete(){
            var x = confirm("Deseja realmente excluir o usuário?");
            if (x){
                return true;
            }else{
                return false;
            }
        }
    </script>
</body>
</html>

resources/views/usuario/create.blade.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Rubik&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{URL::asset('/css/create.css')}}">
    <link rel="shortcut icon" href="{{URL::asset('/image/favicon.ico')}}">
    <title>Registro</title>
</head>
<body>
    <div class="container col-lg-5 col-md-8 col-sm-10 shadow p-3 mt-5 mb-5">
        <div class="content">
            <div class="w-100">
                <img src="{{URL::asset('/image/brand.png')}}" class="mx-auto d-block brand-img" alt='shopmee brand'>
            </div>

            <p class="text-center mt-4">Inscreva-se em nossa newsletter e receba semanalmente <strong>conteúdo sobre negócios e dicas para aumentar suas vendas.</strong></p>

            <form action="{{route('usuario.store')}}" method="POST" class="mt-5 needs-validation novalidate">
                @csrf
                <div class="form-group w-100">
                    <input type="email" class="form-control p-3 ipn-type ipn" id="exampleInputEmail1" name="email" aria-describedby="emailHelp" maxlength="64" placeholder="Comece informando seu melhor e-mail" required>
                </div>
                <div class="form-group mt-3">
                    <input type="text" class="form-control p-3 ipn-type ipn" id="validationCustom01" maxlength="64" name="nome" placeholder="Agora seu nome" required>
                    <div class="invalid-feedback">
                        Por favor, escolha um nome de usuário.
                    </div>
                </div>
                <button class="btn w-100 ipn-type sbm-btn" type="submit">ME INSCREVER</button>
            </form>
        </div>
    </div>

    
    {{-- Bootstrap --}}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

resources/views/usuario/edit.blade.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Rubik&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{URL::asset('/css/create.css')}}">
    <link rel="shortcut icon" href="{{URL::asset('/image/favicon.ico')}}">
    <title>Editar Usuário</title>
</head>
<body>
    
    <div class="container col-lg-5 col-md-8 col-sm-10 shadow p-3 mt-5 mb-5">
        <div class="content">
            <div class="w-100">
                <img src="{{URL::asset('/image/brand.png')}}" class="mx-auto d-block brand-img" alt='shopmee brand'>
            </div>

            <p class="text-left mt-4">Olá <strong>{{$usuario->nome}}</strong>, insira os campos abaixo e seus dados serão editados.</p>

            <form action="{{route('usuario.update', $usuario->id)}}" method="POST" class="mt-5 needs-validation novalidate">
                @method('PUT')
                @csrf
                <div class="form-group w-100">
                    <label for="email">E-mail</label>
                    <input type="email" class="form-control p-3 ipn-type ipn" id="exampleInputEmail1" name="email" aria-describedby="emailHelp" maxlength="64" placeholder="{{$usuario->email}}" required>
                </div>
                <div class="form-group mt-3">
                    <label for="email">Nome</label>
                    <input type="text" class="form-control p-3 ipn-type ipn" maxlength="64" name="nome" placeholder="{{$usuario->nome}}" required>
                  </div>
                <button class="btn w-100 ipn-type sbm-btn" type="submit">Editar</button>
            </form>
        </div>
    </div>

    
    {{-- Bootstrap --}}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

resources/views/usuario/failure.blade.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Rubik&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{URL::asset('/css/confirmation.css')}}">
    <link rel="shortcut icon" href="{{URL::asset('/image/favicon.ico')}}">
    <title>Falha</title>
</head>
<body>
    <div class="container col-lg-5 col-md-8 col-sm-10 shadow p-3 mt-5 mb-5">
        <div class="content">
            <div class="w-100 mt-3">
                <img src="{{URL::asset('/image/failure.png')}}" class="mx-auto d-block failure" alt='success'>
            </div>

            <p class="text-center p mt-4 mb-3">Não foi possível se cadastrar, <span class="text-primary">{{$request->nome}}</span>, já existe um usuário cadastrado com o email <span class="text-primary">{{$request->email}}.</span></p>

            <div class="w-100 text-right mb-4">
                <a class="btn initial-page mr-3" href="{{route('usuario.index')}}">Página inicial</a>
            </div>
        </div>
    </div>

    
    {{-- Bootstrap --}}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

resources/views/usuario/success.blade.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Rubik&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{URL::asset('/css/confirmation.css')}}">
    <link rel="shortcut icon" href="{{URL::asset('/image/favicon.ico')}}">
    <title>Registrado</title>
</head>
<body>
    <div class="container col-lg-5 col-md-8 col-sm-10 shadow p-3 mt-5 mb-5">
        <div class="content">
            <div class="w-100 mt-3">
                <img src="{{URL::asset('/image/success.png')}}" class="mx-auto d-block success" alt='success'>
            </div>

            <p class="text-center p mt-4 mb-3">Obrigado por se cadastrar, <span class="text-primary">{{$usuario->nome}}</span>, um e-mail com seus dados foi enviado para <span class="text-primary">{{$usuario->email}}.</span></p>

            <div class="w-100 text-right mb-4">
                <a class="btn initial-page mr-3" href="{{route('usuario.index')}}">Página inicial</a>
            </div>
        </div>
    </div>

    
    {{-- Bootstrap --}}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>